"""
<<valueobject>> Permiso (enumeracion)
"""
from enum import Enum


class Permiso(str, Enum):
    RESERVAR_ITEM = "RESERVAR_ITEM"
    SOLICITAR_PRESTAMO = "SOLICITAR_PRESTAMO"
    RENOVAR_PRESTAMO = "RENOVAR_PRESTAMO"
    CONSULTAR_HISTORIAL_PROPIO = "CONSULTAR_HISTORIAL_PROPIO"
    CONSULTAR_PRESTATARIOS = "CONSULTAR_PRESTATARIOS"
    REGISTRAR_ITEM_INVENTARIO = "REGISTRAR_ITEM_INVENTARIO"
    ACTUALIZAR_ESTADO_ITEM = "ACTUALIZAR_ESTADO_ITEM"
    CONFIRMAR_RESERVA = "CONFIRMAR_RESERVA"
    REGISTRAR_ENTREGA_PRESTAMO = "REGISTRAR_ENTREGA_PRESTAMO"
    REGISTRAR_DEVOLUCION_PRESTAMO = "REGISTRAR_DEVOLUCION_PRESTAMO"
    CONFIGURAR_POLITICAS = "CONFIGURAR_POLITICAS"
    GESTIONAR_USUARIOS_Y_ROLES = "GESTIONAR_USUARIOS_Y_ROLES"
    GENERAR_SANCION_MANUAL = "GENERAR_SANCION_MANUAL"
    LEVANTAR_SANCION = "LEVANTAR_SANCION"
    CONSULTAR_HISTORIAL_GLOBAL = "CONSULTAR_HISTORIAL_GLOBAL"
